# Generated by Django 6.0.6 on 2026-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('disease_type', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('obesity', 'Obesity')], max_length=20)),
            ],
        ),
    ]
