# Generated by Django 6.0.7 on 2026-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_email_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodscan',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='minerals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='portion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='vitamins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodscan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
