# Generated by Django 6.0.7 on 2026-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodscan_fiber_foodscan_minerals_foodscan_portion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodscan',
            name='better_healthy_alternative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='confidence_score',
            field=models.CharField(default='0%', max_length=20),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='daily_intake_percentage',
            field=models.CharField(default='0%', max_length=20),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='health_score',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='risk_level',
            field=models.CharField(default='🟢', max_length=20),
        ),
    ]
