# Generated by Django 6.0.7 on 2026-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_foodscan_better_healthy_alternative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodscan',
            name='ingredients_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='usefulness_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
